server:
  port: 9000
spring:
  profiles:
    active: development
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/asso-kz
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non-null
    visibility:
      field: any
app:
  public_routes: /oauth/token,/public/**,/sms/sign-up/generate,/version,/status,/actuator/**

jwt:
  password:
    encoder:
      secret: oZr417KU7ipPoCCGY0-cPcGu0PpT1_aG9o-BD1KcnN3BpZPrLcNKgcF9QXXJwrY50Whd7Ij51t45oD0ctn-Vo032uFoMtnNzvzpOFq
      iteration: 33
      key_length: 256
  secret: w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-K #This Secret For JWT HS256 Signature Algorithm MUST Have 256 bits KeySize
  expiration: 28800 # token expiration in seconds

sms:
  user:
    url: "http://kazinfoteh.org:9507/api"
    login: 'mangistautaxi1'
    password: 'Ojd9Lenml'
